shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@5.7.2
  - semver@6.3.1

overrides:
  vite: ^8.2.0

minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-core@0.2.7'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.2.7'
  - '@voidzero-dev/vite-plus-darwin-x64@0.2.7'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.7'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.2.7'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.2.7'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.2.7'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.7'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.2.7'
  - vite-plus@0.2.7
