/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IEpAvatar: typeof import('~icons/ep/avatar')['default']
    IEpCloseBold: typeof import('~icons/ep/close-bold')['default']
    IEpFilter: typeof import('~icons/ep/filter')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpSort: typeof import('~icons/ep/sort')['default']
    IEpStarFilled: typeof import('~icons/ep/star-filled')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IEpWarnTriangleFilled: typeof import('~icons/ep/warn-triangle-filled')['default']
  }
}
